Index/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path, include

from main import views

app_name = "main"


urlpatterns = [
        path('', views.DashboardView.as_view(), name="home"),
        # path("home2/", views.Home2View.as_view(), name="home2"),
        path("home3/", views.Home3View.as_view(), name="home3"),
        path("home4/", views.Home4View.as_view(), name="home4"),
        path("home5/", views.Home5View.as_view(), name="home5"),
        path("crm/", views.CrmView.as_view(), name="crm"),
        path("analytics/", views.AnalyticsView.as_view(), name="analytics"),
        # path("products/", views.ProductsView.as_view(), name="products"),
        path("sales/", views.SalesView.as_view(), name="sales"),
        path("blog/", views.Blog.as_view(), name="blog"),
        path("app-calendar/", views.App_CalendarView.as_view(), name="app-calendar"),
        path("app-profile1/", views.App_Profile_1.as_view(), name="app-profile1"),
        path("app-profile2/", views.App_Profile_2.as_view(), name="app-profile2"),
        path("chart-chartist/", views.Chart_chartist.as_view(), name="chart-chartist"),
        path("chart-chartjs/", views.Chart_chartjs.as_view(), name="chart-chartjs"),
        path("chart-flot/", views.Chart_flot.as_view(), name="chart-flot"),
        path("chart-morris/", views.Chart_morris.as_view(), name="chart-morris"),
        path("chart-peity/", views.Chart_peity.as_view(), name="chart-peity"),
        path("chart-sparkline/", views.Chart_sparkline.as_view(), name="chart-sparkline"),
        path("ecom-checkout/", views.Ecom_CheckoutView.as_view(), name="ecom-checkout"),
        path("ecom-custumers/", views.Ecom_CustomersView.as_view(), name="ecom-customers"),
        path("ecom-invoice/", views.Ecom_InvoiceView.as_view(), name="ecom-invoice"),
        path("ecom-product-grid/", views.Ecom_Product_GridView.as_view(), name="ecom-product-grid"),
        path("email-compose/", views.Email_ComposeView.as_view(), name="email-compose"),
        path("email-inbox/", views.Email_InboxView.as_view(), name="email-inbox"),
        path("email-read/", views.Email_ReadView.as_view(), name="email-read"),
        path("empty-page/", views.Empty_PageView.as_view(), name="empty-page"),
        path("form-ckeditor/", views.Form_CkeditorView.as_view(), name="form-ckeditor"),
        path("form-element/", views.Form_ElementView.as_view(), name="form-element"),
        path("form-pickers/", views.Form_PickersView.as_view(), name="form-pickers"),
        path("form-validation/", views.Form_ValidationView.as_view(), name="form-validation"),
        path("form-wizard/", views.Form_WizardView.as_view(), name="form-wizard"),

        path("users/", include("main.user.urls")),
        path("product/", include("main.product.urls")),
        path("category-tag/", include("main.category-tag.urls")),
        path("ecom-product-detail/<slug:slug>/", views.Ecom_Product_DetailView.as_view(), name="ecom-product-detail"),

]

main/user/urls.py
from django.urls import path

from .views import Add_UserDeleteView, Add_UserListView, Add_UserCreateView, Add_UserUdateView


urlpatterns = [
        path("", Add_UserListView.as_view(), name="add_user-list"),
        path("create/", Add_UserCreateView.as_view(), name="add_user-create"),
        path("<int:pk>/", Add_UserUdateView.as_view(), name="add_user-update"),
        path("delete/<int:pk>/", Add_UserDeleteView.as_view(), name="add_user-delete"),
        ]

main/user/forms.py
from django import forms
from main.models import Users

class Add_UserForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Users
        fields = ['name', 'surname', 'gender', 'phone_number', 'birth_date', 'email', 'region', 'city_or_district', 'profile_image']
        
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Ismingizni kiriting'}),
            'surname': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Familiyangizni kiriting'}),
            'gender': forms.Select(attrs={'class': 'form-control'}, choices=[('', 'Tanlash')] + list(Users.GENDER_CHOICES)),  # 'Tanlash' qo'shildi
            "email": forms.TextInput(attrs={"class": "form-control form-label",'placeholder': 'Email yozing'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Telefon raqamingiz'}),
            'birth_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'region': forms.Select(attrs={'class': 'form-control'}, choices=[('', 'Tanlash')] + list(Users.REGION_CHOICES)),  # 'Tanlash' qo'shildi
            'city_or_district': forms.Select(attrs={'class': 'form-control'}, choices=[('', 'Tanlash')] + list(Users.CITY_CHOICES)),  # 'Tanlash' qo'shildi
            'profile_image': forms.FileInput(attrs={'class': 'form-control', 'type': 'file'})
        }

main/user/views.py
from django.views.generic import ListView

from main.models import Users
from helpers.views import CreateView, UpdateView, DeleteView

from .forms import Add_UserForm

class Add_UserListView(ListView):
    model = Users
    template_name = "apps/users-manager/user.html"
    context_object_name = "users"
    queryset = model.objects.all().order_by("-id")
    paginate_by = 10

    def get_queryset(self):
        object_list = self.queryset
        search = self.request.GET.get("search", None)
        if search:
            object_list = object_list.filter(name__icontains=search)

        return object_list


class Add_UserCreateView(CreateView):
    model = Users
    form_class = Add_UserForm
    template_name = "apps/users-manager/add-admin.html"
    context_object_name = "object"
    success_url = "main:add_user-list"
    success_create_url = "main:add_user-create"
    
    
class Add_UserUdateView(UpdateView):
    model = Users
    template_name = "apps/users-manager/edit-admin.html"
    form_class = Add_UserForm
    context_object_name = "object"
    success_url = "main:add_user-list"
    success_create_url = "main:add_user-update"


class Add_UserDeleteView(DeleteView):
    model = Users
    success_url = "main:add_user-list"

templates/apps/users-manager/add-admin.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
		
		<!--**********************************
            Chat box start
        ***********************************-->
		{% include 'chatbox.html' %}
		<!--**********************************
            Chat box End
        ***********************************-->
		
		<!--**********************************
            Header start
        ***********************************-->
		{% include 'header.html' %}
        
        <!--**********************************
            Header end ti-comment-alt
        ***********************************-->

        <!--**********************************
            Sidebar start
        ***********************************-->
		{% include 'sidebar.html' with menu_parent="user" menu_submenu="user-create" %}

        <!--**********************************
            Sidebar end
        ***********************************-->
		
		<!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">
            <!-- row -->
			<div class="container-fluid">
				<!-- row -->
				<div class="row">
					
					<div class="col-xl-12 col-lg-12">
						<div class="card profile-card card-bx m-b30">
							<div class="card-header">
								<h6 class="title">Account setup</h6>
							</div>
							<form class="profile-form" method="post" enctype="multipart/form-data" action="">
                                {% csrf_token %}

								<div class="card-body">
									<div class="row">
										<div class="col-sm-6 m-b30">
											<label class="form-label">ismi</label>
											<input type="text" class="form-control" value="John" name="name">
										</div>
										<div class="col-sm-6 m-b30">
											<label class="form-label">Familiyasi</label>
											<input type="text" class="form-control" value="Couter" name="surname">
										</div>
										
										<div class="col-sm-6 m-b30">
											<label class="form-label">Jinsi</label>
											<select class="default-select form-control" id="validationCustom05" name="gender">
												<option  data-display="Select">Please select</option>
												<option value="html">Erkak</option>
												<option value="css">Ayol</option>
												<option value="javascript">Boshqa</option>
											</select>
										</div>
										<div class="col-sm-6 m-b30">
											<label class="form-label">Tug'ilgan kuni</label>
											<input type="date" class="form-control" name="birth_date">
										</div>
										<div class="col-sm-6 m-b30">
											<label class="form-label">Telefon Raqami</label>
											<input type="text" class="form-control" value="+123456789" name="phone_number">
										</div>
										<div class="col-sm-6 m-b30">
											<label class="form-label">Email Adresi</label>
											<input type="text" class="form-control" value="demo@gmail.com" name="email">
										</div>
										<div class="col-sm-6 m-b30">
											<label class="form-label">Viloyati</label>
											<select class="default-select form-control" id="validationCustom01" name="region">
												<option  data-display="Select">Please select</option>
												<option value="russia">Andijon</option>
												<option value="canada">Namangan</option>
												<option value="china">Farg'ona</option>
												<option value="india">Toshkent</option>
											</select>
										</div>
										<div class="col-sm-6 m-b30">
											<label class="form-label">Shahar yoki Tumani</label>
											<select class="default-select form-control" id="validationCustom02" name="city_or_district">
												<option  data-display="Select">Please select</option>
												<option>Andijon Shahar</option>
												<option>Andijon Tuman</option>
												<option>Shahrixon Tumani</option>
												<option>Ontin Ko'l Tumani</option>
											</select>
										</div>
										<div class="col-sm-6 m-b30">
											<label class="form-label">Profil Rasm</label>
											<input type="file" class="form-control" name="profile_image">
										</div>
									</div>
								</div>
								



								<div class="tab-content main-editor">
									<div class="card-body">
										<div class="row">
											{% for field in form %}
											<div class="col-sm-6 m-b30">
	
												<label class="form-label" for="{{field.auto_id}}">
													{% if field.field.required %}
													<b>{{field.label}}</b>
													{% else %}
													{{field.label}}
													{% endif %}
												</label>
												<div class="col-lg-9 col-md-9 col-sm-12">
													
													<span style="color:red;">{{field.errors}}</span>
													
													{{field}}
												</div>
											</div>
											{% endfor %}
										</div>


										<div class="card-footer">
											<button type="submit" class="btn btn-primary" name="save-create">Qo'shish</button>
											<a href="page-register.html" class="btn-link">Forgot your password?</a>
										</div>
							</form>
						</div>
					</div>
				</div>
            </div>
        </div>
        <!--**********************************
            Content body end
        ***********************************-->
		
		
{% endblock %}

templates/apps/users-manager/edit-admin.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
		
		<!--**********************************
            Chat box start
        ***********************************-->
		{% include 'chatbox.html' %}
		<!--**********************************
            Chat box End
        ***********************************-->
		
		<!--**********************************
            Header start
        ***********************************-->
		{% include 'header.html' %}
        
        <!--**********************************
            Header end ti-comment-alt
        ***********************************-->

        <!--**********************************
            Sidebar start
        ***********************************-->
		{% include 'sidebar.html' with menu_parent="user" menu_submenu="add_user-update" %}

        <!--**********************************
            Sidebar end
        ***********************************-->
		
		<!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">
            <!-- row -->
			<div class="container-fluid">
				<!-- row -->
				<div class="row">
					
					<div class="col-xl-12 col-lg-12">
						<div class="card profile-card card-bx m-b30">
							<div class="card-header">
								<h6 class="title">Account setup</h6>
							</div>
							<form class="profile-form" method="post" enctype="multipart/form-data" action="">
                                {% csrf_token %}

								<div class="card-body">
									<div class="row">
										{% for field in form %}
										<div class="col-sm-6 m-b30">

											<label class="form-label" for="{{field.auto_id}}">
												{% if field.field.required %}
												<b>{{field.label}}</b>
												{% else %}
												{{field.label}}
												{% endif %}
											</label>
											<div class="col-lg-12 col-md-12 col-sm-12">
												
												<span style="color:red;">{{field.errors}}</span>
												
												{{field}}
											</div>
										</div>
										{% endfor %}
									</div>
								</div>


									<div class="card-footer">
										<button type="submit" class="btn btn-primary" name="saved">Saqlash</button>
										<a href="{% url 'main:add_user-list' %}" class="btn-link">Ortga Qaytish</a>
									</div>
							</form>
						</div>
					</div>
				</div>
            </div>
        </div>
        <!--**********************************
            Content body end
        ***********************************-->
		
		
{% endblock %}

templates/apps/users-manager/user.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

		
		<!--**********************************
            Chat box start
        ***********************************-->
		{% include 'chatbox.html' %}
		<!--**********************************
            Chat box End
        ***********************************-->
		
		<!--**********************************
		Header start
        ***********************************-->
		{% include 'header.html' %}
			
        <!--**********************************
            Header end ti-comment-alt
        ***********************************-->

        <!--**********************************
            Sidebar start
        ***********************************-->
		{% include 'sidebar.html' with menu_parent="user" menu_submenu="add_user-list" %}
		
        <!--**********************************
            Sidebar end
        ***********************************-->
		
		<!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">
            <!-- row -->
			<div class="container-fluid">
				<div class="row">
					<div class="d-flex justify-content-between align-items-center mb-4">
						<h4 class="heading mb-0">Users</h4>
						<div class="d-flex align-items-center">
							<ul class="nav nav-pills mix-chart-tab user-m-tabe" id="pills-tab" role="tablist">
								<li class="nav-item" role="presentation">
									<button class="nav-link" data-series="colm" id="pills-colm-tab" data-bs-toggle="pill" data-bs-target="#pills-colm" type="button" role="tab"  aria-selected="false">
									 <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24  24" version="1.1" class="svg-main-icon">
											<g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
												<rect x="0" y="0" width="24" height="24"/>
												<path d="M10.5,5 L19.5,5 C20.3284271,5 21,5.67157288 21,6.5 C21,7.32842712 20.3284271,8 19.5,8 L10.5,8 C9.67157288,8 9,7.32842712 9,6.5 C9,5.67157288 9.67157288,5 10.5,5 Z M10.5,10 L19.5,10 C20.3284271,10 21,10.6715729 21,11.5 C21,12.3284271 20.3284271,13 19.5,13 L10.5,13 C9.67157288,13 9,12.3284271 9,11.5 C9,10.6715729 9.67157288,10 10.5,10 Z M10.5,15 L19.5,15 C20.3284271,15 21,15.6715729 21,16.5 C21,17.3284271 20.3284271,18 19.5,18 L10.5,18 C9.67157288,18 9,17.3284271 9,16.5 C9,15.6715729 9.67157288,15 10.5,15 Z" fill="#000000"/>
												<path d="M5.5,8 C4.67157288,8 4,7.32842712 4,6.5 C4,5.67157288 4.67157288,5 5.5,5 C6.32842712,5 7,5.67157288 7,6.5 C7,7.32842712 6.32842712,8 5.5,8 Z M5.5,13 C4.67157288,13 4,12.3284271 4,11.5 C4,10.6715729 4.67157288,10 5.5,10 C6.32842712,10 7,10.6715729 7,11.5 C7,12.3284271 6.32842712,13 5.5,13 Z M5.5,18 C4.67157288,18 4,17.3284271 4,16.5 C4,15.6715729 4.67157288,15 5.5,15 C6.32842712,15 7,15.6715729 7,16.5 C7,17.3284271 6.32842712,18 5.5,18 Z" fill="#000000" opacity="0.3"/>
											</g>
										</svg>
									</button>
								</li>
								<li class="nav-item" role="presentation">
									<button class="nav-link active" data-series="list" id="pills-week-tab" data-bs-toggle="pill" data-bs-target="#pills-list" type="button" role="tab"  aria-selected="true">
										
										<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="svg-main-icon">
										<g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
											<rect x="0" y="0" width="24" height="24"/>
											<rect fill="#000000" opacity="0.3" x="4" y="4" width="4" height="4" rx="1"/>
											<path d="M5,10 L7,10 C7.55228475,10 8,10.4477153 8,11 L8,13 C8,13.5522847 7.55228475,14 7,14 L5,14 C4.44771525,14 4,13.5522847 4,13 L4,11 C4,10.4477153 4.44771525,10 5,10 Z M11,4 L13,4 C13.5522847,4 14,4.44771525 14,5 L14,7 C14,7.55228475 13.5522847,8 13,8 L11,8 C10.4477153,8 10,7.55228475 10,7 L10,5 C10,4.44771525 10.4477153,4 11,4 Z M11,10 L13,10 C13.5522847,10 14,10.4477153 14,11 L14,13 C14,13.5522847 13.5522847,14 13,14 L11,14 C10.4477153,14 10,13.5522847 10,13 L10,11 C10,10.4477153 10.4477153,10 11,10 Z M17,4 L19,4 C19.5522847,4 20,4.44771525 20,5 L20,7 C20,7.55228475 19.5522847,8 19,8 L17,8 C16.4477153,8 16,7.55228475 16,7 L16,5 C16,4.44771525 16.4477153,4 17,4 Z M17,10 L19,10 C19.5522847,10 20,10.4477153 20,11 L20,13 C20,13.5522847 19.5522847,14 19,14 L17,14 C16.4477153,14 16,13.5522847 16,13 L16,11 C16,10.4477153 16.4477153,10 17,10 Z M5,16 L7,16 C7.55228475,16 8,16.4477153 8,17 L8,19 C8,19.5522847 7.55228475,20 7,20 L5,20 C4.44771525,20 4,19.5522847 4,19 L4,17 C4,16.4477153 4.44771525,16 5,16 Z M11,16 L13,16 C13.5522847,16 14,16.4477153 14,17 L14,19 C14,19.5522847 13.5522847,20 13,20 L11,20 C10.4477153,20 10,19.5522847 10,19 L10,17 C10,16.4477153 10.4477153,16 11,16 Z M17,16 L19,16 C19.5522847,16 20,16.4477153 20,17 L20,19 C20,19.5522847 19.5522847,20 19,20 L17,20 C16.4477153,20 16,19.5522847 16,19 L16,17 C16,16.4477153 16.4477153,16 17,16 Z" fill="#000000"/>
										</g>
									</svg>
									</button>
								</li>
							</ul>
							<a href="{% url 'main:add_user-create' %}" class="btn btn-primary btn-sm ms-2">+ Add User</a>
						</div>
					</div>
					<div class="col-xl-12 active-p">
					<div class="tab-content" id="pills-tabContent">
						<div class="tab-pane fade show active" id="pills-list" role="tabpanel" aria-labelledby="pills-list-tab">
						<div class="row">
							{% for user in users %}
							<div class="col-xl-3 col-lg-4 col-sm-6">
								<div class="card">
									<div class="card-body">
										<div class="card-use-box">
											<div class="crd-bx-img">
											   <img src="{{ user.profile_image.url }}" class="rounded-circle" alt="">
											</div>
											<div class="card__text">
											  <h4 class="mb-0">{{user.name}} {{user.surname}}</h4>
											  <p>{{user.email}}</p>
											</div>
											<ul class="card__info">
											  
											</ul>
											<ul class="post-pos">
												<li>
													<span class="card__info__stats">Telfon Raqami: </span>
													<span>{{user.phone_number}}</span>
												</li>
												<li>
													<span class="card__info__stats">Tug'ilgan Sanasi: </span>
													<span>{{user.birth_date}}</span>
												</li>
											</ul>
											<div>
												<a href="{% url 'main:add_user-update' user.pk %}" class="btn btn-primary btn-sm me-2">O'zgartirish</a>
											</div>	
										</div>
									</div>
								</div>
							</div>
							{% endfor %}
						</div>
						</div>
						<div class="tab-pane fade" id="pills-colm" role="tabpanel" aria-labelledby="pills-colm-tab">
							<div class="card">
								<div class="card-body px-0">
								  <div class="table-responsive active-projects user-tbl  dt-filter">
									<table id="user-tbl" class="table shorting">
										<thead>
											
										</thead>
										{% for user in users %}
										<tbody>
											<tr>
												<td>
													<div class="d-flex align-items-center">
														<img src="{{ user.profile_image.url }}" class="avatar rounded-circle" alt="">
														<p class="mb-0 ms-2">{{user.name}} {{user.surname}}</p>	
													</div>
												</td>
												<td>{{user.email}}</td>
												<td>{{user.birth_date}}</td>
												<td>{{user.region}}</td>
												<td>{{user.city_or_district}}</td>
												<td>
													<div class="dropdown">
														<div class="btn-link" data-bs-toggle="dropdown" aria-expanded="false">
															<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
																<path d="M11 12C11 12.5523 11.4477 13 12 13C12.5523 13 13 12.5523 13 12C13 11.4477 12.5523 11 12 11C11.4477 11 11 11.4477 11 12Z" stroke="#737B8B" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
																<path d="M18 12C18 12.5523 18.4477 13 19 13C19.5523 13 20 12.5523 20 12C20 11.4477 19.5523 11 19 11C18.4477 11 18 11.4477 18 12Z" stroke="#737B8B" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
																<path d="M4 12C4 12.5523 4.44772 13 5 13C5.55228 13 6 12.5523 6 12C6 11.4477 5.55228 11 5 11C4.44772 11 4 11.4477 4 12Z" stroke="#737B8B" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
															</svg>
														</div>
														<div class="dropdown-menu dropdown-menu-right" style="">
															<a class="dropdown-item" href="{% url 'main:add_user-update' user.pk %}">O'zgartirish</a>
															<a class="dropdown-item" href="{% url 'main:add_user-delete' user.pk %}">O'chirish</a>
														</div>
													</div>
												</td>
											</tr>
										</tbody>
										{% endfor %}
										
									</table>
								</div>
							   </div>
							</div>
						
						</div>
					</div>
					</div>
				</div>
			</div>
        </div>
		
        <!--**********************************
            Content body end
        ***********************************-->
		
{% endblock %}